from pathlib import Path
root=Path('/tmp/floholmen')

def shell(title, eyebrow, heading, lead, body):
    return f'''<!doctype html><html lang="no"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="{title} | Fløholmen AS"><title>{title} | Fløholmen AS</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"></head><body><div class="topbar"><div class="wrap"><span>Fløholmen AS · Mekanisk verksted</span><span><a href="tel:+4795855072">+47 958 55 072</a> · <a href="mailto:post@floholmen.no">post@floholmen.no</a></span></div></div><header><div class="wrap nav"><a class="brand" href="index.html"><span class="mark">F</span><span><strong>Fløholmen</strong><small>Elektro · Mekanisk</small></span></a><nav class="navlinks"><a href="index.html#tjenester">Tjenester</a><a href="om-oss.html">Om oss</a><a href="maskinpark.html">Maskinpark</a><a href="referanser.html">Referanser</a><a class="cta" href="kontakt.html">Ta kontakt ↗</a></nav></div></header><main><section class="page-hero"><div class="wrap"><p class="eyebrow">{eyebrow}</p><h1>{heading}</h1><p>{lead}</p></div></section><section class="content"><div class="wrap">{body}</div></section></main><footer><div class="wrap footer-inner"><strong>Fløholmen AS</strong><span>© 2026 · Mekanisk verksted · 5937 Bøvågen</span></div></footer></body></html>'''

pages={
' tjenester.html'.strip():shell('Våre tjenester','Fløholmen · hva vi gjør','Kompetanse som holder','Fra enkeltoppdrag til sertifiserte løfteinnretninger – vi hjelper deg fra behov til ferdig leveranse.','''<div class="service-list"><article class="service-tile"><span class="num">01 / 03</span><h3>CNC-<br>maskinering</h3><p>Nøyaktig maskinering og produksjon av komponenter etter tegning og spesifikasjon.</p><a class="button" href="cnc-maskinering.html">Les mer ↗</a></article><article class="service-tile"><span class="num">02 / 03</span><h3>Elektro-<br>motorer</h3><p>Reparasjon og service på elektromotorer, med fokus på driftssikkerhet og kort nedetid.</p><a class="button" href="elektromotorer.html">Les mer ↗</a></article><article class="service-tile"><span class="num">03 / 03</span><h3>Mekanisk<br>verksted</h3><p>Produksjon av løfteinnretninger på bestilling – levert med nødvendige sertifikater.</p><a class="button" href="mekanisk-verksted.html">Les mer ↗</a></article></div>'''),
'cnc-maskinering.html':shell('CNC-maskinering','Tjenester · 01','CNC-maskinering','Vi har utstyr for CNC-dreiing, boring, fresing og produksjon av presise komponenter i små og større serier.','''<div class="intro-grid"><div><h2>Presisjon etter tegning</h2><p>På CNC-maskinering i form av dreiing har vi alt fra små, enkle CNC-styrte dreiebenker til avanserte dreiesenter med verktøyveksler og 3 akser. Vi produserer komponenter etter kundens tegninger og spesifikasjoner.</p><p>Ta kontakt for å diskutere et oppdrag eller en konkret komponent.</p><a class="button" href="kontakt.html">Send forespørsel ↗</a></div><div class="aside"><h3>Maskinering</h3><p>Solid erfaring, moderne maskiner og en praktisk tilnærming til toleranser, materialer og levering.</p><div class="list dark-list"><div><span>Prosess</span><b>Dreiing · fresing · boring</b></div><div><span>Leveranse</span><b>Etter tegning</b></div><div><span>Fokus</span><b>Nøyaktighet og drift</b></div></div></div></div>'''),
'elektromotorer.html':shell('Elektromotorer','Tjenester · 02','Service som holder motoren i gang','Reparasjon og service på elektromotorer, med fokus på driftssikkerhet og kort nedetid.','''<div class="intro-grid"><div><h2>Minst mulig stans</h2><p>Vi reparerer og utfører service på elektromotorer og komponenter for industri og maritime aktører. Målet er å finne en riktig og kostnadseffektiv løsning som får utstyret raskt tilbake i drift.</p><p>Vi utfører også service på taljer, inkludert skifte av slitedeler og inspeksjon av alle komponenter. Dette vet vi er langt rimeligere enn å kjøpe nytt.</p><a class="button" href="kontakt.html">Snakk med oss ↗</a></div><div class="aside"><h3>Service</h3><p>Vi planlegger arbeidet tett med kunden slik at driftsstansen blir så kort som mulig.</p><div class="list dark-list"><div><span>Motorer</span><b>Reparasjon og service</b></div><div><span>Taljer</span><b>Inspeksjon og slitedeler</b></div><div><span>Planlegging</span><b>Tett kundedialog</b></div></div></div></div>'''),
'mekanisk-verksted.html':shell('Mekanisk verksted','Tjenester · 03','Mekanisk verksted','Fra spesialdeler til løfteinnretninger – vi produserer og tilpasser løsninger for krevende miljøer.','''<div class="intro-grid"><div><h2>Bygd for jobben</h2><p>Vi produserer løfteinnretninger på bestilling, med nødvendige sertifikater. Verkstedet har lang erfaring med produksjon, reparasjon og service av taljer, kraner og stålkonstruksjoner.</p><p>Vi utfører også ombygging av stålkonstruksjoner, tannhjulsproduksjon, sliping, stansing, glassblåsing, lodding og liming av bremsebelegg.</p><a class="button" href="kontakt.html">Start en dialog ↗</a></div><div class="aside"><h3>Verksted</h3><p>Erfaring fra industrien, fleksibel kapasitet og sertifisert arbeid.</p><div class="list dark-list"><div><span>Areal</span><b>2 500 m² under tak</b></div><div><span>Traverskran</span><b>1 500 m² dekket</b></div><div><span>Leveranse</span><b>Løfteinnretninger</b></div></div></div></div>'''),
'om-oss.html':shell('Om oss','Fløholmen siden 1987','Et verksted du kan stole på','Fløholmen AS kombinerer lang erfaring med presisjon, sertifisert arbeid og en praktisk tilnærming til hver leveranse.','''<div class="intro-grid"><div><h2>Fra Bøvågen til hele verden</h2><p>Fløholmen ble stiftet i 1987 og overtok lokalene og produksjonen fra Munck Gruppen. I dag er vi underleverandør for Munck Crane AS, Umoe Schat-Harding AS og Dreggen Crane AS.</p><p>Produktene herfra er spredt over hele verden, fra atomkraftverk i Sveits til skipsverft i Midtøsten og Russland, industri og stålverk i Amerika, Europa og Østen. Fra båter på alle verdenshav til fryselagre i Norge finnes elektromotorer og krankomponenter som er produsert her i Bøvågen.</p><p>Vi har over 40 års erfaring på produksjon, reparasjon og service av taljer.</p></div><div class="aside"><h3>Nøkkeltall</h3><div class="list dark-list"><div><span>Etablert</span><b>1987</b></div><div><span>Lokaler</span><b>2 500 m²</b></div><div><span>Lokasjon</span><b>Vestsiden av Radøy</b></div><div><span>Tilkomst</span><b>15 m kai · 6 m dybde</b></div></div></div></div>'''),
'kontakt.html':shell('Kontakt oss','Finn oss','Nær kunden. Nær sjøen.','Grei tilkomst fra både vei og sjø gjør Fløholmen til et effektivt utgangspunkt for oppdrag på Vestlandet.','''<div class="contact-grid"><div class="contact-box"><p class="kicker">Besøk verkstedet</p><h2>Fløholmen AS</h2><p>5937 Bøvågen<br>Radøy, Vestland</p><p>Omtrent én times biltur nord for Bergen og 30 minutter til Mongstad. Vi har også god tilkomst fra sjøen med 15 meter betongkai og minste dybde 6 meter.</p></div><div class="contact-box orange"><p class="kicker">Ta kontakt</p><h2>Har du et oppdrag?</h2><p>Ta kontakt for en uforpliktende prat om maskinering, service eller en spesialtilpasset løsning.</p><a href="tel:+4795855072">+47 958 55 072 ↗</a><a href="mailto:post@floholmen.no">post@floholmen.no ↗</a></div></div>'''),
}
for name,html in pages.items(): (root/name).write_text(html,encoding='utf-8')

# Gallery pages
refs=''.join(f'<figure><img src="assets/referanser/{i}.jpg" alt="Referansearbeid fra Fløholmen {i}" loading="lazy"><figcaption>Leveranse fra Fløholmen</figcaption></figure>' for i in [1,2,3,5,6,7,8,9,10,11])
(root/'referanser.html').write_text(shell('Referanser','Arbeid vi har levert','Fra idé til ferdig leveranse','Vi har kompetanse innen reparasjon av plastbåter og motorer, deleproduksjon i nylon og metaller, og service på kraner og taljer.','''<div class="intro-grid"><div><h2>Noe av det vi har levert</h2><p>Vi utfører service på taljer, skifter slitedeler og inspiserer alle komponenter. Vi planlegger servicen tett med kunden slik at driftsstansen blir så kort som mulig.</p><p>Her er et utvalg av arbeid fra verkstedet vårt.</p></div><div class="aside"><h3>Eksempler</h3><div class="list dark-list"><div><span>Industri</span><b>Heistromler og kranmotorer</b></div><div><span>Maskinering</span><b>Akslinger og tannhjul</b></div><div><span>Maritimt</span><b>Redningsbåt-komponenter</b></div></div></div></div><div class="gallery">'''+refs+'''</div>'''),encoding='utf-8')
machines=''.join(f'<figure><img src="assets/maskinpark/{i}.jpg" alt="Maskinpark Fløholmen {i}" loading="lazy"><figcaption>Maskinpark · {i:02d}</figcaption></figure>' for i in range(1,13))
(root/'maskinpark.html').write_text(shell('Maskinpark','Utstyr og kapasitet','Maskinparken vår','Et allsidig verksted med utstyr for maskinering, sliping, boring, fresing, stansing og mer.','''<div class="machine-grid"><div class="machine-copy"><h2>Riktig utstyr for jobben</h2><p>Maskinparken vår gir oss fleksibilitet til å løse både små og større oppdrag. Vi kombinerer tradisjonelt verkstedhåndverk med CNC-kapasitet.</p><ul><li>Platesaks, maks 3 150 × 6,3 mm</li><li>Planslipemaskin 200 × 600 mm</li><li>Rundsliping og tannstikking</li><li>Fresemaskin og boremaskin</li><li>Revolver- og CNC-dreiebenker</li><li>Maskineringssenter og båndsag</li></ul><a class="button" href="kontakt.html">Spør om kapasitet ↗</a></div><div class="gallery">'''+machines+'''</div></div>'''),encoding='utf-8')

# Update service card links in homepage and nav links in existing page.
p=root/'index.html'; s=p.read_text(encoding='utf-8'); s=s.replace('href="#tjenester" class="cta"','href="kontakt.html" class="cta"').replace('href="#tjenester">Se våre tjenester','href="index.html#tjenester">Se våre tjenester').replace('href="#om-oss"','href="om-oss.html"').replace('href="#kontakt"','href="kontakt.html"')
s=s.replace('<article class="service"><div><span class="service-number">01 / 03</span>','<a href="cnc-maskinering.html" class="service"><div><span class="service-number">01 / 03</span>').replace('</article><article class="service"><div><span class="service-number">02 / 03</span>','</a><a href="elektromotorer.html" class="service"><div><span class="service-number">02 / 03</span>').replace('</article><article class="service"><div><span class="service-number">03 / 03</span>','</a><a href="mekanisk-verksted.html" class="service"><div><span class="service-number">03 / 03</span>').replace('</article></div></div></section>','</a></div></div></section>')
p.write_text(s,encoding='utf-8')
# Legacy filename aliases for old inbound links.
for old,new in [('cncmaskinering.html','cnc-maskinering.html'),('mekanisk_verksted.html','mekanisk-verksted.html'),('omoss.html','om-oss.html')]:
    (root/old).write_text(f'<!doctype html><meta http-equiv="refresh" content="0; url={new}"><link rel="canonical" href="{new}">',encoding='utf-8')
